### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by chrismatix** [airyhq/bazel-tools#1]
- [x] Add the license
- [x] Add code of conduct 
- [x] Improve the readme
  - [x] Add `git_repository` installation to top of README.md
  - [x] how to contribute section
  - [x] mention the code of conduct
  - [x] Introduce the project as part of the airy open source things (link to docs.airy.co)
- [x] github action for buildifier
- [x] Add a contributing.md file (the mono repo one can be used for the structure)
- [x] Add Pr labeler
- [x] Add release drafter
